# Generated by Django 5.2 on 2025-05-07 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='celebrity',
            name='awards',
            field=models.TextField(blank=True, default='8'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='projects',
            field=models.TextField(blank=True, default='78'),
        ),
        migrations.AddField(
            model_name='celebrity',
            name='years_active',
            field=models.TextField(blank=True, default='5'),
        ),
    ]
