# Generated by Django 5.2 on 2025-05-07 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_celebrity_awards_celebrity_followers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='followers',
            field=models.TextField(default='2.8M'),
        ),
    ]
