# Generated by Django 5.2 on 2025-05-07 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_show'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='followers',
            field=models.TextField(default='2.8'),
        ),
    ]
