# Generated by Django 5.2 on 2025-05-07 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_celebrity_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='celebrity',
            name='followers',
            field=models.TextField(blank=True, default='2.8'),
        ),
    ]
