# Generated by Django 5.2 on 2025-05-11 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smmboost', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='last_checked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='remains',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='start_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
